### ISSUE TITLE
Garmin Connect not syncing

### ISSUE THREAD

**Issue by pcragone** [cpfair/tapiriik#294]
I've just started using tapiriik and connect Garmin Connect, Strava, Runkeeper, and Dropbox, and the latter three sync all my activities but Garmin Connect won't seem to do so.  Any reason why I get this error for all my activities?

```
Garmin Connect: There was a problem uploading this activity to Garmin Connect.
```

**Comment by noln** [comment]
I just came here to raise that same issue. Usual reset password on GC then reconnect didn't work. Presuming it's a GC API change as production version was working fine earlier in the week but now isn't uploading activities to GC at all.

**Comment by RobDickson** [comment]
It's hasn't been working very well since Christmas:
https://github.com/cpfair/tapiriik/issues/273

**Comment by stevespeirs** [comment]
Same for me - very sporadic this week.

**Comment by srjinatl** [comment]
Same issue here - last successful sync for me was a ride I did on 2/12. Nothing since then,...hopefully will get fixed soon....

**Comment by RobDickson** [comment]
@stevespeirs Sporadic is better than not at all though.

@srjinatl It's not been that bad for me. At least it worked once or twice in January, but nothing for 2.5 months is bad.

I wish I could offer to help, but I don't know enough about coding.

**Comment by MattB111** [comment]
For me nothing has synced from Strava to GC since 13th February. When I log into tapiriik it just says "Queuing..."

I have tried disconnecting GC and reconnecting, but didn't make a difference.

**Comment by jturkel** [comment]
I had similar problems with syncing not working starting sometime after 2/11. I had Tapiriik configured to sync activities from June 2014. I changed this to only sync activities since Jan 2017 which seemed to fix things (immediately as well as for subsequent activities). Maybe requesting ~3 years of activities from Garmin was causing performance issues?

**Comment by srjinatl** [comment]
@jturkel I tried changing mine to the same - since Jan 2017 - and still having errors sync'ing to Garmin - not having problems syncing to Runkeeper for same activities. So definitely seems for me at least to be specific to Garmin Connect endpoint.

**Comment by cpfair** [comment]
I believe this issue should be fixed in 51226cc012b433e64f2c418d54f3ccde1c75dab9

**Comment by srjinatl** [comment]
Not for me - still not syncing any recent activities to Garmin. Tried disconnecting Tapirik and reconnecting it to my Garmin account as well - and that made no difference - activities still not syncing to Garmin.

**Comment by RobDickson** [comment]
It hasn't fixed it for me either, but thanks for trying. Like for others in this thread, it's been playing up since before Christmas.

I am synchronising from Garmin to Strava and Dropbox.

**Comment by RobDickson** [comment]
In fact, it's even worse now. Before the fix, I could get Garmin to sync by changing the date to sync from. Now it won't sync at all.

**Comment by MattB111** [comment]
Thanks Colin. Just checked and all my runs since 13th Feb have synced fine on my account and my wife's account.

**Comment by RobDickson** [comment]
It took two days to sync. I suppose if people have several months of unsynchronised activities to synchronise, it will take a while.

**Comment by wojtek-b** [comment]
I think garmin connect is not syncing again...

**Comment by RobDickson** [comment]
Maybe, but it hasn't been synchronising properly since before Christmas.
